### ISSUE TITLE
[!] 299 vulnerabilities found [10929 packages audited]

### ISSUE THREAD

**Issue by jimoquinn** [gianluca-venturini/crypto-plumber#2]
WTF?

oquinn@sugarTRD:~/crypto-plumber$ npm install
npm WARN notice [SECURITY] is-my-json-valid has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=is-my-json-valid&version=2.16.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] constantinople has 1 critical vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=constantinople&version=3.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.7.2 install /home/oquinn/crypto-plumber/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-59_binding.node
Download complete  ] - :
Binary saved to /home/oquinn/crypto-plumber/node_modules/node-sass/vendor/linux-x64-59/binding.node
Caching binary to /home/oquinn/.npm/node-sass/4.7.2/linux-x64-59_binding.node

> node-sass@4.7.2 postinstall /home/oquinn/crypto-plumber/node_modules/node-sass
> node scripts/build.js

Binary found at /home/oquinn/crypto-plumber/node_modules/node-sass/vendor/linux-x64-59/binding.node
Testing binary
Binary is fine

> nodemon@1.13.0 postinstall /home/oquinn/crypto-plumber/node_modules/nodemon
> node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')"

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**added 880 packages from 617 contributors in 14.452s
[!] 299 vulnerabilities found [10929 packages audited]
    Severity: 188 low | 89 moderate | 22 high**
    Run `npm audit` for more detail

oquinn@sugarTRD:~/crypto-plumber$ npm build-ts

**Comment by gianluca-venturini** [comment]
Not relevant.
